image: "ruby:2.7"

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - gem install bundler
  - bundle install --path /cache
  - bundle exec rake db:test:prepare
  - bundle exec rake test

deploy:
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=breadtubetv --api-key=$HEROKU_API_KEY
  only:
  - master