development:
  adapter: postgresql
  database: breadtubetv_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: breadtubetv_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: breadtubetv_production
  pool: 5
  timeout: 5000