shared:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL", "") %>
  host: <%= ENV.fetch("DB_HOST", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  pool: 5
  timeout: 5000

development: &shared
  database: <%= ENV.fetch("POSTGRES_DB", "breadtubetv_development") %>

test: &shared
  database: <%= ENV.fetch("POSTGRES_DB", "breadtubetv_test") %>

production: &shared
  database: <%= ENV.fetch("POSTGRES_DB", "breadtubetv_production") %>