shared:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL", "") %>
  host: <%= ENV.fetch("DB_HOST", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  pool: 5
  timeout: 5000

development: &shared
  database: breadtubetv_development_rebuild
  
test: &shared
  database: breadtubetv_test

production: &shared
  database: breadtubetv_production